In [2]:
import numpy as np

# Experiment with the compute_valid_moves to see if it works for a simplified board (5x5)

In [47]:
state = np.zeros((5, 5, 5))

attacker_layout = np.array([[0, 0, 1, 0, 0], 
                            [0, 0, 0, 0, 0],
                            [1, 0, 0, 0, 1],
                            [0, 0, 0, 0, 0],
                            [0, 0, 1, 0, 0]])

defender_layout = np.array([[0, 0, 0, 0, 0], 
                            [0, 0, 1, 0, 0],
                            [0, 1, 2, 1, 0],
                            [0, 0, 1, 0, 0],
                            [0, 0, 0, 0, 0]])

state[0] = attacker_layout
state[1] = defender_layout
board_size = state.shape[1]

In [48]:
state[0] + state[1]

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 2., 1., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [6]:
# In: state (current state), x-position of piece, y-position of piece
# Out: list of all possible actions where action a = ((x, y), (new_x, new_y))
def actions_for_piece(state, x, y):
    actions = []

    board_size = state.shape[1]

    # the position of every piece
    full_board = state[0] + state[1]

    throne = (board_size // 2, board_size // 2)
    # can the piece move up?
    if x > 0:
        pos_x = x
        pos_y = y 
        # continue until on the edge or about to collide with another piece
        while pos_x > 0 and not full_board[pos_x - 1, y]:
            pos_x -= 1
            # the action isn't possible if the destination is the throne, except if the piece is the king
            if ((full_board[x, y] == 2 and ((pos_x, y) == throne))) or (((pos_x, y) != throne)):
                actions.append(((x, y), (pos_x, y)))

    # can the piece move down?
    if x < board_size - 1:
        pos_x = x
        pos_y = y
        # continue until on the edge or about to collide with another piece
        while pos_x < board_size - 1 and not full_board[pos_x + 1, y]:
            pos_x += 1

            if ((full_board[x, y] == 2 and ((pos_x, y) == throne))) or (((pos_x, y) != throne)):
                actions.append(((x, y), (pos_x, y)))

    # can the piece move left?
    if y > 0:
        pos_x = x
        pos_y = y
        while pos_y > 0 and not full_board[x, pos_y - 1]:
            pos_y -= 1

            if ((full_board[x, y] == 2 and ((x, pos_y) == throne))) or (((x, pos_y) != throne)):
                actions.append(((x, y), (x, pos_y)))
                
    # can the piece move right?
    if y < board_size - 1:
        pos_x = x
        pos_y = y
        while pos_y < board_size - 1 and not full_board[x, pos_y + 1]:
            pos_y += 1

            if ((full_board[x, y] == 2 and ((x, pos_y) == throne))) or (((x, pos_y) != throne)):
                actions.append(((x, y), (x, pos_y)))

    return actions

In [4]:
# In: state (current state)
# Out: list of all possible actions for all pieces of the current player 
#      where action a = ((x, y), (new_x, new_y))
def compute_valid_moves(state):
    actions = []

    board_size = state.shape[1]

    full_board = state[0] + state[1]

    throne = (board_size // 2, board_size // 2)

    turn = int(np.max(state[2]))

    for i in range(board_size):
            for j in range(board_size):
                if state[turn, i, j]:
                    piece_actions = actions_for_piece(state, i, j)

                    # this isn't the most efficient way of doing this 
                    # but I wanted to have a seperate helper method
                    for a in piece_actions:
                        actions.append(a)
    return actions

In [51]:
compute_valid_moves(state)

[((0, 2), (0, 1)),
 ((0, 2), (0, 0)),
 ((0, 2), (0, 3)),
 ((0, 2), (0, 4)),
 ((2, 0), (1, 0)),
 ((2, 0), (0, 0)),
 ((2, 0), (3, 0)),
 ((2, 0), (4, 0)),
 ((2, 4), (1, 4)),
 ((2, 4), (0, 4)),
 ((2, 4), (3, 4)),
 ((2, 4), (4, 4)),
 ((4, 2), (4, 1)),
 ((4, 2), (4, 0)),
 ((4, 2), (4, 3)),
 ((4, 2), (4, 4))]

## Checking the time complexity

In [60]:
import timeit

state = np.zeros((hnef_vars.NUM_CHNLS, 9, 9))
attacker_layout = np.array([[0,0,0,1,1,1,0,0,0],
                            [0,0,0,0,1,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0],
                            [1,0,0,0,0,0,0,0,1],
                            [1,0,0,0,0,0,0,0,1],
                            [1,0,0,0,0,0,0,0,1],
                            [0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,1,0,0,0,0],
                            [0,0,0,1,1,1,0,0,0]])
defender_layout = np.array([[0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,1,0,0,0,0],
                            [0,0,0,0,1,0,0,0,0],
                            [0,0,1,1,2,1,1,0,0],
                            [0,0,0,0,1,0,0,0,0],
                            [0,0,0,0,1,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0]])
state[hnef_vars.ATTACKER] = attacker_layout
state[hnef_vars.DEFENDER] = defender_layout
board_size = state.shape[1]

times = []
for i in range(1000):

    start = timeit.default_timer()
    compute_valid_moves(state)
    end = timeit.default_timer()
    times.append(end - start)

print(np.mean(times), np.std(times))

0.00018949400016572327 7.144579193593266e-05


In [61]:
state = np.zeros((hnef_vars.NUM_CHNLS, 11, 11))
attacker_layout = np.array([[0,0,0,1,1,1,1,1,0,0,0],
                            [0,0,0,0,0,1,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0,0,0],
                            [1,0,0,0,0,0,0,0,0,0,1],
                            [1,0,0,0,0,0,0,0,0,0,1],
                            [1,1,0,0,0,0,0,0,0,1,1],
                            [1,0,0,0,0,0,0,0,0,0,1],
                            [1,0,0,0,0,0,0,0,0,0,1],
                            [0,0,0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,1,0,0,0,0,0],
                            [0,0,0,1,1,1,1,1,0,0,0]])
                    
defender_layout = np.array([[0,0,0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,1,0,0,0,0,0],
                            [0,0,0,0,1,1,1,0,0,0,0],
                            [0,0,0,1,1,2,1,1,0,0,0],
                            [0,0,0,0,1,1,1,0,0,0,0],
                            [0,0,0,0,0,1,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0,0,0],
                            [0,0,0,0,0,0,0,0,0,0,0]])
state[hnef_vars.ATTACKER] = attacker_layout
state[hnef_vars.DEFENDER] = defender_layout

board_size = state.shape[1]

times = []
for i in range(1000):

    start = timeit.default_timer()
    compute_valid_moves(state)
    end = timeit.default_timer()
    times.append(end - start)

print(np.mean(times), np.std(times))

0.000279090400057612 7.538956275792639e-05


# Experiment with check_capture

In [10]:
import hnef_vars

In [12]:
# Method for checking whether a capture has taken place
# In: state (current state), action (action taken by current player)
# Out: state (new state)
def check_capture(state, action):
    # current player
    player = int(np.max(state[hnef_vars.TURN_CHNL]))
    # other player
    other_player = np.abs(player - 1)
    # defender
    df = hnef_vars.DEFENDER
    # attacker
    at = hnef_vars.ATTACKER
    # board size
    board_size = state.shape[1]
    # throne location
    throne = (board_size // 2, board_size // 2)

    # new location of moved piece
    x, y = action[1]

    ## capturing normal pieces normally
    
    # capturing upwards
    if x > 1 and state[other_player][x-1][y] == 1 and state[player][x-2][y] > 0:
        state[other_player][x-1][y] = 0

    # capturing downwards
    if x < board_size - 2 and state[other_player][x+1][y] == 1 and state[player][x+2][y] >  0:
        state[other_player][x+1][y] = 0
    
    # capturing left
    if y > 1 and state[other_player][x][y-1] == 1 and state[player][x][y-2] > 0:
        state[other_player][x][y-1] = 0

    # capturing right
    if y < board_size - 2 and state[other_player][x][y+1] == 1 and state[player][x][y+2] > 0:
        state[other_player][x][y+1] = 0
    
    ## capturing normal pieces with the throne
    
    # if the king is on the throne then the white pieces cant be captured in this way
    if not (player == at and state[df][throne[0]][throne[0]] == 2):
        print(state[player][x-2][y] == throne)

        # capturing upwards
        if x > 1 and state[other_player][x-1][y] == 1 and np.mean(state[player][x-2][y] == throne):
            state[other_player][x-1][y] = 0
        # capturing downwards
        elif x < board_size - 2 and state[other_player][x+1][y] == 1 and np.mean(state[player][x+2][y] == throne):
            state[other_player][x+1][y] = 0
        # capturing left
        elif y > 1 and state[other_player][x][y-1] == 1 and np.mean(state[player][x][y-2] == throne):
            state[other_player][x][y-1] = 0
        # capturing right
        elif y < board_size - 2 and state[other_player][x][y+1] == 1 and np.mean(state[player][x][y+2] == throne):
            state[other_player][x][y+1] = 0
    
    ## capturing the king normally

    # capturing upwards
    if x > 1 and state[df][x-1][y] == 2 and state[player][x-2][y] > 0:
        state[df][x-1][y] = 0
        state[hnef_vars.DONE_CHNL] = 1
        return state

    # capturing downwards
    if x < board_size - 2 and state[df][x+1][y] == 2 and state[player][x+2][y] > 0:
        state[df][x+1][y] = 0
        state[hnef_vars.DONE_CHNL] = 1
        return state
    
    # capturing left
    if y > 1 and state[df][x][y-1] == 2 and state[player][x][y-2] > 0:
        state[df][x][y-1] = 0
        state[hnef_vars.DONE_CHNL] = 1
        return state

    # capturing right
    if y < board_size - 2 and state[df][x][y+1] == 2 and state[player][x][y+2] > 0:
        state[df][x][y+1] = 0
        state[hnef_vars.DONE_CHNL] = 1
        return state

    ## capturing the king on the throne
    if (state[df][throne[0]][throne[0]] == 2 
        and state[at][throne[0]-1][throne[0]] 
        and state[at][throne[0]+1][throne[0]] 
        and state[at][throne[0]][throne[0]-1] 
        and state[at][throne[0]][throne[0]]+1):
        state[df][throne[0]][throne[0]] = 0
        state[hnef_vars.DONE_CHNL] = 1
        return state

    ## capturing the king next to the throne

    if player == at:
        # king is above throne
        if state[df][throne[0]-1][throne[0]] == 2 and state[at][throne[0]-1][throne[0]-1] and state[at][throne[0]-1][throne[0]+1] and state[at][throne[0]-2][throne[0]]:
            state[df][throne[0]-1][throne[0]] = 0
            state[hnef_vars.DONE_CHNL] = 1
            return state
        # king is below throne  
        elif state[df][throne[0]+1][throne[0]] == 2 and state[at][throne[0]+1][throne[0]-1] and state[at][throne[0]+1][throne[0]+1] and state[at][throne[0]+2][throne[0]]:
            state[df][throne[0]+1][throne[0]] = 0
            state[hnef_vars.DONE_CHNL] = 1
            return state
        # king is left of throne 
        elif state[df][throne[0]][throne[0]-1] == 2 and state[at][throne[0]-1][throne[0]-1] and state[at][throne[0]+1][throne[0]-1] and state[at][throne[0]][throne[0]-2]:
            state[df][throne[0]][throne[0]-1] = 0
            state[hnef_vars.DONE_CHNL] = 1
            return state
        # king is right of throne 
        elif state[df][throne[0]][throne[0]+1] == 2 and state[at][throne[0]-1][throne[0]+1] and state[at][throne[0]+1][throne[0]+1] and state[at][throne[0]][throne[0]+2]:
            state[df][throne[0]][throne[0]+1] = 0
            state[hnef_vars.DONE_CHNL] = 1
            return state

    return state

In [13]:


state = np.zeros((5, 5, 5))

attacker_layout = np.array([[0, 0, 0, 0, 0], 
                            [0, 0, 1, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 1, 0, 0]])

defender_layout = np.array([[0, 0, 0, 0, 0], 
                            [0, 0, 0, 0, 0],
                            [0, 0, 2, 0, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0]])

state[0] = attacker_layout
state[1] = defender_layout
# state[2, 0, 0] = 1
board_size = state.shape[1]

test_action = ((4, 2), (3, 2))

valid_moves = compute_valid_moves(state)

assert test_action in valid_moves

turn = int(np.max(state[hnef_vars.TURN_CHNL]))
# move the piece
state[turn][test_action[0][0]][test_action[0][1]] = 0
state[turn][test_action[1][0]][test_action[1][1]] = 1

print(state[0]+state[1])
new_state = check_capture(state, test_action)
print(new_state[0]+new_state[1])

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 2. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# note: because actiosn is only the list of actions for the current player
# this check should only be done when it is the defenders turn
# unless we change that later, which we might want to do
def check_enclosure(state, action):
    board_size = state.shape[1] # get board size
    wall_positions = [] # holds wall positions for specific board size

    # populate wall positions array with tuples of (row_index, col_index)
    for i in range(board_size): # row index loop
        for j in range(board_size): # col index loop
            # bottom or top wall indices
            if i == 0 or i == board_size - 1:
                wall_positions.append((i,j))
            # side walls
            elif j == 0 or j == board_size -1:
                wall_positions.append((i,j))

    # list comprehension to check if a wall position is within the list of 
    # possible actions for the defender
    # appends those locations if they exist in the action list
    # wall_moves = [pos for pos in wall_positions if pos in action]

    # not as pretty but still works
    # should we break early or add some terminating condition?
    wall_moves = []
    
    for pos in wall_positions:
        for a in action:
            if a[1] == pos:
                wall_moves.append(pos)

    # if no defender pieces can move to a wall then they are either enclosed or 
    # there are no remaining defender pieces
    # either way the game is over and the attacker wins
    if len(wall_moves) == 0:
        return True, hnef_vars.ATTACKER
    else:
        return False, -1




In [23]:
state = np.zeros((5, 5, 5))
# 0 wall moves
action_no_wall_moves = [((1,1), (2,1)), ((2,3), (3,3))] 
# 2 wall moves
action_with_wall_moves = [((1,1), (1,0)), ((2,2), (2,3)), ((3,1), (3,3))] 

print(check_enclosure(state, action_no_wall_moves))

print(check_enclosure(state, action_with_wall_moves))

(True, 0)
(False, -1)


In [25]:
print(len(action_no_wall_moves))

2
